-- simEigen lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'
require 'functional'

return function(obj)
    obj['Matrix:abs'] = wrap(obj['Matrix:abs'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:acos'] = wrap(obj['Matrix:acos'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:add'] = wrap(obj['Matrix:add'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:asin'] = wrap(obj['Matrix:asin'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:atan'] = wrap(obj['Matrix:atan'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:block'] = wrap(obj['Matrix:block'], function(origFunc)
        return function(...)
            local i, j, p, q = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(i, j, p, q)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:blockassign'] = wrap(obj['Matrix:blockassign'], function(origFunc)
        return function(...)
            local m, i, j, p, q = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(m, i, j, p, q)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:ceil'] = wrap(obj['Matrix:ceil'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:col'] = wrap(obj['Matrix:col'], function(origFunc)
        return function(...)
            local j = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(j)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:coldata'] = wrap(obj['Matrix:coldata'], function(origFunc)
        return function(...)
            local j = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(j)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:cols'] = wrap(obj['Matrix:cols'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:copy'] = wrap(obj['Matrix:copy'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:cos'] = wrap(obj['Matrix:cos'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:count'] = wrap(obj['Matrix:count'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:cross'] = wrap(obj['Matrix:cross'], function(origFunc)
        return function(...)
            local v2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(v2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:data'] = wrap(obj['Matrix:data'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:deg'] = wrap(obj['Matrix:deg'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:det'] = wrap(obj['Matrix:det'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:div'] = wrap(obj['Matrix:div'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:dot'] = wrap(obj['Matrix:dot'], function(origFunc)
        return function(...)
            local v2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(v2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:exp'] = wrap(obj['Matrix:exp'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:eye'] = wrap(obj['Matrix:eye'], function(origFunc)
        return function(...)
            local n = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(n)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:floor'] = wrap(obj['Matrix:floor'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:horzcat'] = wrap(obj['Matrix:horzcat'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:iabs'] = wrap(obj['Matrix:iabs'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:iacos'] = wrap(obj['Matrix:iacos'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:iadd'] = wrap(obj['Matrix:iadd'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:iasin'] = wrap(obj['Matrix:iasin'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:iatan'] = wrap(obj['Matrix:iatan'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:iceil'] = wrap(obj['Matrix:iceil'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:icos'] = wrap(obj['Matrix:icos'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:ideg'] = wrap(obj['Matrix:ideg'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:idiv'] = wrap(obj['Matrix:idiv'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:iexp'] = wrap(obj['Matrix:iexp'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:ifloor'] = wrap(obj['Matrix:ifloor'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:iintdiv'] = wrap(obj['Matrix:iintdiv'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:ilog'] = wrap(obj['Matrix:ilog'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:ilog2'] = wrap(obj['Matrix:ilog2'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:ilog10'] = wrap(obj['Matrix:ilog10'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:imax'] = wrap(obj['Matrix:imax'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:imin'] = wrap(obj['Matrix:imin'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:imod'] = wrap(obj['Matrix:imod'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:imul'] = wrap(obj['Matrix:imul'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:intdiv'] = wrap(obj['Matrix:intdiv'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:inversetransform'] = wrap(obj['Matrix:inversetransform'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:irad'] = wrap(obj['Matrix:irad'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:isin'] = wrap(obj['Matrix:isin'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:ismatrix'] = wrap(obj['Matrix:ismatrix'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'any'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:isorthogonal'] = wrap(obj['Matrix:isorthogonal'], function(origFunc)
        return function(...)
            local tol = checkargsEx(
                {level=1},
                {
                    {type = 'double', default = 1e-6},
                },
                ...
            )
            local _rets = {origFunc(tol)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:isqrt'] = wrap(obj['Matrix:isqrt'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:isub'] = wrap(obj['Matrix:isub'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:isvector'] = wrap(obj['Matrix:isvector'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'any'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:itan'] = wrap(obj['Matrix:itan'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:itimes'] = wrap(obj['Matrix:itimes'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:item'] = wrap(obj['Matrix:item'], function(origFunc)
        return function(...)
            local i, j = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(i, j)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:kron'] = wrap(obj['Matrix:kron'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:linspace'] = wrap(obj['Matrix:linspace'], function(origFunc)
        return function(...)
            local low, high, count = checkargsEx(
                {level=1},
                {
                    {type = 'float'},
                    {type = 'float'},
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(low, high, count)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:log'] = wrap(obj['Matrix:log'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:log2'] = wrap(obj['Matrix:log2'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:log10'] = wrap(obj['Matrix:log10'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:max'] = wrap(obj['Matrix:max'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:maxcoeff'] = wrap(obj['Matrix:maxcoeff'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:maxcoeff'] = wrap(obj['Matrix:maxcoeff'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:min'] = wrap(obj['Matrix:min'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:maxcoeff'] = wrap(obj['Matrix:maxcoeff'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:mod'] = wrap(obj['Matrix:mod'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:mul'] = wrap(obj['Matrix:mul'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:norm'] = wrap(obj['Matrix:norm'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:normalize'] = wrap(obj['Matrix:normalize'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:normalized'] = wrap(obj['Matrix:normalized'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:pinv'] = wrap(obj['Matrix:pinv'], function(origFunc)
        return function(...)
            local b, damping = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                    {type = 'float'},
                },
                ...
            )
            local _rets = {origFunc(b, damping)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:print'] = wrap(obj['Matrix:print'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:prod'] = wrap(obj['Matrix:prod'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:rad'] = wrap(obj['Matrix:rad'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:reshaped'] = wrap(obj['Matrix:reshaped'], function(origFunc)
        return function(...)
            local rows, cols = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(rows, cols)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:row'] = wrap(obj['Matrix:row'], function(origFunc)
        return function(...)
            local i = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(i)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:rowdata'] = wrap(obj['Matrix:rowdata'], function(origFunc)
        return function(...)
            local i = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(i)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:rows'] = wrap(obj['Matrix:rows'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:setcol'] = wrap(obj['Matrix:setcol'], function(origFunc)
        return function(...)
            local j, col = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(j, col)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:setcoldata'] = wrap(obj['Matrix:setcoldata'], function(origFunc)
        return function(...)
            local j, data = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'table', item_type = 'float'},
                },
                ...
            )
            local _rets = {origFunc(j, data)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:setdata'] = wrap(obj['Matrix:setdata'], function(origFunc)
        return function(...)
            local data = checkargsEx(
                {level=1},
                {
                    {type = 'table', item_type = 'float'},
                },
                ...
            )
            local _rets = {origFunc(data)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:setitem'] = wrap(obj['Matrix:setitem'], function(origFunc)
        return function(...)
            local i, j, data = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'table', item_type = 'float'},
                },
                ...
            )
            local _rets = {origFunc(i, j, data)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:setrow'] = wrap(obj['Matrix:setrow'], function(origFunc)
        return function(...)
            local i, row = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(i, row)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:setrowdata'] = wrap(obj['Matrix:setrowdata'], function(origFunc)
        return function(...)
            local i, data = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'table', item_type = 'float'},
                },
                ...
            )
            local _rets = {origFunc(i, data)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:sin'] = wrap(obj['Matrix:sin'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:sqrt'] = wrap(obj['Matrix:sqrt'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:norm'] = wrap(obj['Matrix:norm'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:sub'] = wrap(obj['Matrix:sub'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:prod'] = wrap(obj['Matrix:prod'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:svd'] = wrap(obj['Matrix:svd'], function(origFunc)
        return function(...)
            local computeThinU, computeThinV, b = checkargsEx(
                {level=1},
                {
                    {type = 'bool', default = false},
                    {type = 'bool', default = false},
                    {type = 'table', default = nil},
                },
                ...
            )
            local _rets = {origFunc(computeThinU, computeThinV, b)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:tan'] = wrap(obj['Matrix:tan'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:times'] = wrap(obj['Matrix:times'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:trace'] = wrap(obj['Matrix:trace'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:transform'] = wrap(obj['Matrix:transform'], function(origFunc)
        return function(...)
            local v = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(v)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:transpose'] = wrap(obj['Matrix:transpose'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:transposed'] = wrap(obj['Matrix:transposed'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix:vertcat'] = wrap(obj['Matrix:vertcat'], function(origFunc)
        return function(...)
            local m2 = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m2)}
            return table.unpack(_rets)
        end
    end)

    obj['Matrix'] = wrap(obj['Matrix'], function(origFunc)
        return function(...)
            local rows, cols, data = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'table', item_type = 'float'},
                },
                ...
            )
            local _rets = {origFunc(rows, cols, data)}
            return table.unpack(_rets)
        end
    end)

    obj['Vector'] = wrap(obj['Vector'], function(origFunc)
        return function(...)
            local size, data = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'table', item_type = 'float'},
                },
                ...
            )
            local _rets = {origFunc(size, data)}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:data'] = wrap(obj['Quaternion:data'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:fromaxisangle'] = wrap(obj['Quaternion:fromaxisangle'], function(origFunc)
        return function(...)
            local axis, angle = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                    {type = 'double'},
                },
                ...
            )
            local _rets = {origFunc(axis, angle)}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:fromeuler'] = wrap(obj['Quaternion:fromeuler'], function(origFunc)
        return function(...)
            local euler = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(euler)}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:fromrotation'] = wrap(obj['Quaternion:fromrotation'], function(origFunc)
        return function(...)
            local r = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(r)}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:imul'] = wrap(obj['Quaternion:imul'], function(origFunc)
        return function(...)
            local o = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(o)}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:inv'] = wrap(obj['Quaternion:inv'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:isquaternion'] = wrap(obj['Quaternion:isquaternion'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'any'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:mul'] = wrap(obj['Quaternion:mul'], function(origFunc)
        return function(...)
            local o = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(o)}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:slerp'] = wrap(obj['Quaternion:slerp'], function(origFunc)
        return function(...)
            local t, q2 = checkargsEx(
                {level=1},
                {
                    {type = 'double'},
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(t, q2)}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:toaxisangle'] = wrap(obj['Quaternion:toaxisangle'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:toeuler'] = wrap(obj['Quaternion:toeuler'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion:torotation'] = wrap(obj['Quaternion:torotation'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Quaternion'] = wrap(obj['Quaternion'], function(origFunc)
        return function(...)
            local data = checkargsEx(
                {level=1},
                {
                    {type = 'table', item_type = 'float', default = {}},
                },
                ...
            )
            local _rets = {origFunc(data)}
            return table.unpack(_rets)
        end
    end)

    obj['Pose:data'] = wrap(obj['Pose:data'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Pose:fromtransform'] = wrap(obj['Pose:fromtransform'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Pose:inv'] = wrap(obj['Pose:inv'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Pose:ispose'] = wrap(obj['Pose:ispose'], function(origFunc)
        return function(...)
            local m = checkargsEx(
                {level=1},
                {
                    {type = 'any'},
                },
                ...
            )
            local _rets = {origFunc(m)}
            return table.unpack(_rets)
        end
    end)

    obj['Pose:mul'] = wrap(obj['Pose:mul'], function(origFunc)
        return function(...)
            local o = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(o)}
            return table.unpack(_rets)
        end
    end)

    obj['Pose:totransform'] = wrap(obj['Pose:totransform'], function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            local _rets = {origFunc()}
            return table.unpack(_rets)
        end
    end)

    obj['Pose'] = wrap(obj['Pose'], function(origFunc)
        return function(...)
            local t, q = checkargsEx(
                {level=1},
                {
                    {type = 'table'},
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(t, q)}
            return table.unpack(_rets)
        end
    end)

end
