-- simIM lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'
require 'functional'

return function(obj)
    obj['dataURL'] = wrap(obj['dataURL'], function(origFunc)
        return function(...)
            local imgHandle, format = checkargsEx(
                {level=1},
                {
                    {type = 'string'},
                    {type = 'string', default = BMP},
                },
                ...
            )
            local _rets = {origFunc(imgHandle, format)}
            return table.unpack(_rets)
        end
    end)

    obj['getMarkerBitSize'] = wrap(obj['getMarkerBitSize'], function(origFunc)
        return function(...)
            local dictType = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(dictType)}
            return table.unpack(_rets)
        end
    end)

end
