-- simMIDI lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'
require 'functional'

return function(obj)
    obj['processIncomingMessages'] = wrap(obj['processIncomingMessages'], function(origFunc)
        return function(...)
            local midiInPortHandle, channels, funcs = checkargsEx(
                {level=1},
                {
                    {type = 'string'},
                    {type = 'table', item_type = 'int'},
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(midiInPortHandle, channels, funcs)}
            return table.unpack(_rets)
        end
    end)

end
