-- simQML lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'
require 'functional'

return function(obj)
    obj['sendEvent'] = wrap(obj['sendEvent'], function(origFunc)
        return function(...)
            local engine, name, data = checkargsEx(
                {level=1},
                {
                    {type = 'string'},
                    {type = 'string'},
                    {type = 'table'},
                },
                ...
            )
            local _rets = {origFunc(engine, name, data)}
            return table.unpack(_rets)
        end
    end)

    obj['setEventHandler'] = wrap(obj['setEventHandler'], function(origFunc)
        return function(...)
            local engine, funcName = checkargsEx(
                {level=1},
                {
                    {type = 'string'},
                    {type = 'string'},
                },
                ...
            )
            local _rets = {origFunc(engine, funcName)}
            return table.unpack(_rets)
        end
    end)

end
