-- simUI lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'
require 'functional'

return function(obj)
    obj['insertTableRow'] = wrap(obj['insertTableRow'], function(origFunc)
        return function(...)
            local ui, widget, index = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(ui, widget, index)}
            return table.unpack(_rets)
        end
    end)

    obj['removeTableRow'] = wrap(obj['removeTableRow'], function(origFunc)
        return function(...)
            local ui, widget, index = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(ui, widget, index)}
            return table.unpack(_rets)
        end
    end)

    obj['insertTableColumn'] = wrap(obj['insertTableColumn'], function(origFunc)
        return function(...)
            local ui, widget, index = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(ui, widget, index)}
            return table.unpack(_rets)
        end
    end)

    obj['removeTableColumn'] = wrap(obj['removeTableColumn'], function(origFunc)
        return function(...)
            local ui, widget, index = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'int'},
                },
                ...
            )
            local _rets = {origFunc(ui, widget, index)}
            return table.unpack(_rets)
        end
    end)

    obj['setScene3DNodeParam'] = wrap(obj['setScene3DNodeParam'], function(origFunc)
        return function(...)
            local ui, widget, nodeId, paramName, paramValue = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'int'},
                    {type = 'string'},
                    {type = 'any'},
                },
                ...
            )
            local _rets = {origFunc(ui, widget, nodeId, paramName, paramValue)}
            return table.unpack(_rets)
        end
    end)

end
